### ISSUE TITLE
migrate does not migrate tortoise model 

### ISSUE THREAD

**Issue by modekano** [josnin/django-whatsapp-web-clone#7]
when run `python manage.py migrate` does not migrate tortoise model. after run migrate I get table for ChatGroup only no table for ChatMessage

**Comment by josnin** [comment]
> when run `python manage.py migrate` does not migrate tortoise model. after run migrate I get table for ChatGroup only no table for ChatMessage

Tortoise ORM doesn't have its own migration yet, you can try to delete the DB first and recreate

```
rm db.sqlite3.tortoise
```

Btw, We are using asyncio for our Chat consumer, to have the full performance benefits of using async I decided to use Tortoise ORM (since Django ORM doesn't support the async yet)

**Comment by modekano** [comment]
Thanks for your response, 
I did remove the `db.sqlite3.tortoise` using `rm db.sqlite3.tortoise` after run migrate again it does not migrate ChatMessage
it should generate another instance of sqlite3 as in settings configuration
```
TORTOISE_INIT = {
    "db_url": "sqlite://db.sqlite3.tortoise",
    "modules" : {
        "models": ["chat.tortoise_models"]
     }
}
```
do I am right?

**Comment by josnin** [comment]
Yes, and It will recreate when you start entering the chat message

![image](https://user-images.githubusercontent.com/3206118/97098683-e4020d80-16ba-11eb-8f83-331b6726caa9.png)

![image](https://user-images.githubusercontent.com/3206118/97098691-0562f980-16bb-11eb-9731-49a97476f1fe.png)

**Comment by modekano** [comment]
It work now, thanks for your kind support regards

**Comment by Abdul-Rafae-Mohammed** [comment]
Hi, 

I am facing this issue as well. I tried deleting the database and ran the runserver command again but still seeing the same issue. Chat doesn't work. Any suggestions?

**Comment by Abdul-Rafae-Mohammed** [comment]
cursor = self._conn.execute(sql, parameters)
sqlite3.OperationalError: no such table: chat_chatmessage
Internal Server Error: /chat/history/2/
.....
.....
.....
raise OperationalError(exc)
tortoise.exceptions.OperationalError: no such table: chat_chatmessage
HTTP GET /chat/history/2/ 500 [0.07, 127.0.0.1:54758]
